openapi: 3.0.0
info:
  title: OMS Backend (MVP)
  version: 1.0.0
  description: Minimal backend API for sending trading orders to Centroid through an internal FIX engine.

servers:
  - url: http://localhost:8000

paths:

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK

  /orders:
    post:
      summary: Create a new trading order
      description: >
        Creates an order in the local OMS. The order is persisted and then
        routed to the FIX engine which will forward it to Centroid.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
      responses:
        '201':
          description: Order accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid order parameters

    get:
      summary: List orders
      parameters:
        - in: query
          name: clientId
          schema:
            type: string
        - in: query
          name: symbol
          schema:
            type: string
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /orders/{orderId}:
    get:
      summary: Get a single order by ID
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Not found

  /orders/{orderId}/cancel:
    post:
      summary: Cancel an order
      description: >
        Requests cancellation. The FIX engine will send FIX Cancel (35=F)
        to Centroid and update status when the ExecutionReport arrives.
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cancel request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found

  /positions:
    get:
      summary: Get current positions for a client
      parameters:
        - in: query
          name: clientId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Positions list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Position'

components:

  schemas:

    OrderCreateRequest:
      type: object
      required:
        - clientId
        - symbol
        - side
        - type
        - qty
      properties:
        clientId:
          type: string
        symbol:
          type: string
          example: XAUUSD
        side:
          type: string
          enum: [BUY, SELL]
        type:
          type: string
          enum: [MARKET, LIMIT]
        qty:
          type: number
        price:
          type: number
          nullable: true
        timeInForce:
          type: string
          enum: [GTC, DAY, IOC, FOK]
          default: GTC

    Order:
      type: object
      properties:
        id:
          type: string
        clientId:
          type: string
        symbol:
          type: string
        side:
          type: string
        type:
          type: string
        qty:
          type: number
        price:
          type: number
          nullable: true
        status:
          type: string
          enum:
            - NEW
            - PENDING_SEND
            - SENT
            - PARTIALLY_FILLED
            - FILLED
            - REJECTED
            - CANCELED
        cumQty:
          type: number
        avgPx:
          type: number
          nullable: true
        createdAt:
          type: string
        updatedAt:
          type: string

    Position:
      type: object
      properties:
        clientId:
          type: string
        symbol:
          type: string
        netQty:
          type: number
        avgPx:
          type: number
        unrealizedPnl:
          type: number
