#!/usr/bin/env python3
"""
Export the OpenAPI spec generated by the running FastAPI app (source of truth).

Usage:
  python scripts/export_openapi.py

Outputs:
  - openapi.generated.json (always)
  - openapi.generated.yaml (optional, if PyYAML is available)

This script imports app.main:app to ensure the exported spec matches exactly what the
server would serve at /openapi.json.
"""
import json
import os
import sys

# Try to optionally support YAML export if PyYAML is available
try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover
    yaml = None


def main():
    # Import the FastAPI app from the project
    try:
        from app.main import app  # noqa: F401
    except Exception as e:
        print(f"Failed to import app.main:app: {e}")
        sys.exit(1)

    # Build OpenAPI dict via FastAPI
    openapi = app.openapi()

    repo_root = os.path.dirname(os.path.dirname(__file__))
    json_path = os.path.join(repo_root, "openapi.generated.json")
    yaml_path = os.path.join(repo_root, "openapi.generated.yaml")

    # Write JSON (pretty)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(openapi, f, indent=2, ensure_ascii=False)
    print(f"Wrote {json_path}")

    # Optionally write YAML
    if yaml is not None:
        with open(yaml_path, "w", encoding="utf-8") as f:
            yaml.safe_dump(openapi, f, sort_keys=False, allow_unicode=True)
        print(f"Wrote {yaml_path}")
    else:
        print("PyYAML not installed; skipping openapi.generated.yaml.\n"
              "Install with: pip install pyyaml")


if __name__ == "__main__":
    main()
